- name: Get .dotfiles
  ansible.builtin.git:
    repo: git@github.com:duskrunner/.dotfiles.git
    dest: ~/.dotfiles
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  tags:
    - zsh
    - neovim
    - tmux
- name: Install stow
  community.general.pacman:
    name: stow
    state: latest
  tags:
    - zsh
    - neovim
    - tmux
- name: Run stow script
  shell: cd $HOME/.dotfiles && chmod +x ./stow-dotfiles && ./stow-dotfiles
  tags:
    - zsh
    - neovim
    - tmux
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
