- name: Check if .fonts folder is present
  file:
    path: "~/.fonts"
    state: directory
  tags:
    - fonts
    - zsh
- name: Download font regular
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: ~/.fonts/MesloLGS%20NF%20Regular.ttf
  tags:
    - fonts
    - zsh
- name: Download font bold
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: ~/.fonts/MesloLGS%20NF%20Bold.ttf
  tags:
    - fonts
    - zsh

- name: Download font italic
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: ~/.fonts/MesloLGS%20NF%20Italic.ttf
  tags:
    - fonts
    - zsh
- name: Download font bold italic
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: ~/.fonts/MesloLGS%20NF%20Bold%20Italic.ttf
  tags:
    - fonts
    - zsh
