- name: Install fzf
  community.general.pacman:
    name: fzf
    state: latest
  tags:
    - fzf
- name: Make scripts scripts runable
  shell: chmod +x ~/.dotfiles/bin/.local/bin/*
  tags:
    - fzf
