- name: Download latest stable release of neovim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: ~/nvim.tar.gz
  tags:
    - neovim
- name: Unzip neovim
  shell: cd $HOME && tar xzvf nvim.tar.gz && mv nvim-linux64 nvim
  tags:
    - neovim
- name: Update alias in .zshrcz
  shell: echo "alias nvim=~/nvim/bin/nvim" >> ~/.zshrc && echo "alias vim=~/nvim/bin/nvim" >> ~/.zshrc && echo "alias vi=~/nvim/bin/nvim" >> ~/.zshrc
  tags:
    - neovim
- name: Install ripgrep
  apt: name=ripgrep
  tags:
    - neovim
- name: Remove old neovim configs
  shell: rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim
  tags:
    - neovim
- name: Install nvchad
  ansible.builtin.git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    depth: 1
  tags:
    - neovim
