- name: Install node
  community.general.pacman:
    name: nodejs
    state: latest
  tags:
    - node
  community.general.pacman:
    name: npm
    state: latest
  tags:
    - node
- name: Install n
  npm:
    name: n
    global: true
  tags:
    - node
