- name: Install tmux
  community.general.pacman:
    name: tmux
  tags:
    - tmux
- name: Intall tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: $HOME/.tmux/plugins/tpm
  tags:
    - tmux
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
